In [14]:
!pip install folium

Collecting folium
  Downloading folium-0.20.0-py2.py3-none-any.whl.metadata (4.2 kB)
Collecting branca>=0.6.0 (from folium)
  Downloading branca-0.8.2-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: jinja2>=2.9 in /opt/conda/lib/python3.11/site-packages (from folium) (3.1.2)
Requirement already satisfied: numpy in /opt/conda/lib/python3.11/site-packages (from folium) (1.24.4)
Requirement already satisfied: requests in /opt/conda/lib/python3.11/site-packages (from folium) (2.31.0)
Requirement already satisfied: xyzservices in /opt/conda/lib/python3.11/site-packages (from folium) (2023.10.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.11/site-packages (from jinja2>=2.9->folium) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.11/site-packages (from requests->folium) (3.3.0)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.11/site-packages (from requests->folium) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.11/site-packages (from requests->folium) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.11/site-packages (from requests->folium) (2023.7.22)
Downloading folium-0.20.0-py2.py3-none-any.whl (113 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 113.4/113.4 kB 1.1 MB/s eta 0:00:0000:010:01
Downloading branca-0.8.2-py3-none-any.whl (26 kB)
Installing collected packages: branca, folium
Successfully installed branca-0.8.2 folium-0.20.0

In [16]:
from sqlalchemy import create_engine
import geopandas as gpd
import pandas as pd
import folium

pd.set_option("display.max_columns", 100)

In [17]:
def fetch_gdf(sql, dbname):
    url = f"postgresql://postgres:postgres@postgis_container:5432/{dbname}"
    engine = create_engine(url)
    return gpd.read_postgis(sql, engine, geom_col="geom")

In [18]:
sql = """
WITH p19 AS (
    SELECT
        m.name AS mesh_id,
        d.population,
        m.geom
    FROM pop d
    JOIN pop_mesh m
      ON d.mesh1kmid = m.name
    WHERE
        d.year = '2019'
        AND d.month = '04'
        AND d.dayflag = '0'
        AND d.timezone = '0'
),
p20 AS (
    SELECT
        m.name AS mesh_id,
        d.population,
        m.geom
    FROM pop d
    JOIN pop_mesh m
      ON d.mesh1kmid = m.name
    WHERE
        d.year = '2020'
        AND d.month = '04'
        AND d.dayflag = '0'
        AND d.timezone = '0'
)
SELECT
    a.name_2,
    SUM(p20.population) - SUM(p19.population) AS dif,
    a.geom
FROM p19
JOIN p20
  ON p19.mesh_id = p20.mesh_id
JOIN adm2 a
  ON ST_Within(p19.geom, a.geom)
WHERE a.name_1 = 'Saitama'
GROUP BY a.name_2, a.geom
ORDER BY dif DESC;
"""

In [20]:
gdf = fetch_gdf(sql, "gisdb")
gdf.head()

       name_2      dif                                               geom
0   Kawaguchi  29480.0  MULTIPOLYGON (((139.69797 35.79656, 139.69525 ...
1     Saitama  21849.0  MULTIPOLYGON (((139.67781 35.835, 139.66844 35...
2        Sōka  21624.0  MULTIPOLYGON (((139.76509 35.81464, 139.76703 ...
3  Tokorozawa  20081.0  MULTIPOLYGON (((139.50174 35.77707, 139.49945 ...
4        Ageo  15457.0  MULTIPOLYGON (((139.54117 35.94533, 139.54128 ...

In [21]:
def color_by_diff(val):
    if val > 0:
        return "#ef8a62"   # 増加
    elif val < 0:
        return "#67a9cf"   # 減少
    else:
        return "#ffffff"

In [22]:
def show_map(gdf):
    m = folium.Map(location=[36, 139.5], zoom_start=9)

    def style(feature):
        return {
            "fillColor": color_by_diff(feature["properties"]["dif"]),
            "fillOpacity": 0.7,
            "weight": 0
        }

    folium.GeoJson(
        gdf,
        style_function=style
    ).add_to(m)

    return m

In [23]:
display(gdf)
display(show_map(gdf))

          name_2      dif                                               geom
0      Kawaguchi  29480.0  MULTIPOLYGON (((139.69797 35.79656, 139.69525 ...
1        Saitama  21849.0  MULTIPOLYGON (((139.67781 35.835, 139.66844 35...
2           Sōka  21624.0  MULTIPOLYGON (((139.76509 35.81464, 139.76703 ...
3     Tokorozawa  20081.0  MULTIPOLYGON (((139.50174 35.77707, 139.49945 ...
4           Ageo  15457.0  MULTIPOLYGON (((139.54117 35.94533, 139.54128 ...
..           ...      ...                                                ...
65  Tsurugashima  -2787.0  MULTIPOLYGON (((139.38461 35.91415, 139.38211 ...
66      Chichibu  -2955.0  MULTIPOLYGON (((139.10486 35.92281, 139.10542 ...
67         Hanyū  -3217.0  MULTIPOLYGON (((139.50237 36.18904, 139.5136 3...
68      Namegawa  -4018.0  MULTIPOLYGON (((139.33597 36.03778, 139.33992 ...
69         Iruma  -7735.0  MULTIPOLYGON (((139.41441 35.81966, 139.41376 ...

[70 rows x 3 columns]